# Launch & Build.
version: "3.7"
services: 
  front-end:
    build: ./
    command: python3.7 manage.py runserver 0.0.0.0:8000
    container_name: WFML
    tty: true
    ports:
        - 8000:8000
    restart: on-failure
