# Generated by Selenium IDE
from os.path import dirname, abspath
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver import FirefoxOptions

class TestTest1():
  def setup_method(self):
        opts = FirefoxOptions()
        opts.add_argument("--headless")
        self.driver = webdriver.Firefox(options=opts)
        self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://127.0.0.1:8000/wizard/initialize/")
    self.driver.set_window_size(1848, 1053)
    self.driver.find_element(By.ID, "textarea").click()
    self.driver.find_element(By.ID, "textarea").send_keys("""
    Model 3 {
    xor SurrogateType {
        Single
        Compositional
        Portfolio
    }
   Surrogate {
        LinearRegression + {
            Type -> predefined
            [Type = "LinearRegression"]
        }
        GaussianProcessRegressor + {
            Type -> predefined
            [Type = "GaussianProcessRegressor"]
        }
        [if gcard.parent.SurrogateType == "Compositional" then size childs.Context.Objectives == size childs.self]

    }
    [if gcard.self.SurrogateType == "Single" then gcard.self.Surrogate = 'xor']
    [if gcard.self.SurrogateType == "Single" then fcard.self.Surrogate.GaussianProcessRegressor = 1]
    [if gcard.self.SurrogateType == "Single" then fcard.self.Surrogate.LinearRegression = 1]
    [if gcard.self.SurrogateType == "Compositional" then gcard.self.Surrogate = 'or']
    [if gcard.self.SurrogateType == "Portfolio" then gcard.self.Surrogate = 'or']
}

Context {
    Objectives {
        Objective 1..3 {
            test -> integer
        }
    }
}
    """
    )
    self.driver.find_element(By.CSS_SELECTOR, "p > input").click()
    self.driver.find_element(By.ID, "id_0-Fcard.Context.Objectives.Objective").click()
    self.driver.find_element(By.ID, "id_0-Fcard.Context.Objectives.Objective").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.ID, "id_1-Context.Objectives.Objective_0.test").click()
    self.driver.find_element(By.ID, "id_1-Context.Objectives.Objective_0.test").send_keys("1")
    self.driver.find_element(By.ID, "id_1-Context.Objectives.Objective_1.test").send_keys("2")
    self.driver.find_element(By.ID, "id_1-Context.Objectives.Objective_2.test").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "id_2-Fcard.Model_0.Surrogate.LinearRegression").click()
    self.driver.find_element(By.ID, "id_2-Fcard.Model_0.Surrogate.LinearRegression").send_keys("1")
    self.driver.find_element(By.ID, "id_2-Fcard.Model_1.Surrogate.LinearRegression").send_keys("2")
    self.driver.find_element(By.ID, "id_2-Fcard.Model_2.Surrogate.LinearRegression").send_keys("1")
    self.driver.find_element(By.ID, "id_2-Fcard.Model_0.Surrogate.GaussianProcessRegressor").send_keys("1")
    self.driver.find_element(By.ID, "id_2-Fcard.Model_1.Surrogate.GaussianProcessRegressor").send_keys("1")
    self.driver.find_element(By.ID, "id_2-Fcard.Model_2.Surrogate.GaussianProcessRegressor").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#id_2-Gcard\\.Model_0\\.SurrogateType > li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_2-Gcard\\.Model_1\\.SurrogateType > li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_2-Gcard\\.Model_2\\.SurrogateType > li:nth-child(3) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(15)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_3-Gcard\\.Model_0\\.Surrogate > li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_3-Gcard\\.Model_1\\.Surrogate > li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_3-Gcard\\.Model_2\\.Surrogate > li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_3-Gcard\\.Model_2\\.Surrogate > li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
  
