# Generated by Selenium IDE
from os.path import dirname, abspath
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver import FirefoxOptions
from selenium.webdriver.firefox.service import Service

class TestTest2():
  def setup_method(self):
        opts = FirefoxOptions()
        opts.add_argument("--headless")
        serv = Service(executable_path=f'{dirname(dirname(abspath(__file__)))}/geckodriver')
        self.driver = webdriver.Firefox(options=opts,
                                        service=serv)
        self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("http://127.0.0.1:8000/wizard/initialize/")
    self.driver.set_window_size(1848, 1053)
    self.driver.find_element(By.ID, "textarea").click()
    self.driver.find_element(By.ID, "textarea").send_keys("""
    a 2..3 {
	xor b 2..3 {
		c 2..3 {
			d -> integer
		}
		e 2..3 {
			b -> integer 2..3
			c -> integer
			[c > b]
		}
	}
}

b 2..3 {
	c -> integer 2..3 
	[c > 2]
}
    """)
    self.driver.find_element(By.CSS_SELECTOR, "p > input").click()
    self.driver.find_element(By.ID, "id_0-Fcard.b").click()
    self.driver.find_element(By.ID, "id_0-Fcard.b").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.ID, "id_1-Fcard.b_0.c").click()
    self.driver.find_element(By.ID, "id_1-Fcard.b_0.c").send_keys("2")
    self.driver.find_element(By.ID, "id_1-Fcard.b_1.c").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    self.driver.find_element(By.ID, "id_2-b_0.c_0").click()
    self.driver.find_element(By.ID, "id_2-b_0.c_0").send_keys("3")
    self.driver.find_element(By.ID, "id_2-b_0.c_1").send_keys("3")
    self.driver.find_element(By.ID, "id_2-b_1.c_0").send_keys("3")
    self.driver.find_element(By.ID, "id_2-b_1.c_1").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
    self.driver.find_element(By.ID, "id_3-Fcard.a").click()
    self.driver.find_element(By.ID, "id_3-Fcard.a").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "main:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.ID, "id_4-Fcard.a_0.b").click()
    self.driver.find_element(By.ID, "id_4-Fcard.a_0.b").send_keys("2")
    self.driver.find_element(By.ID, "id_4-Fcard.a_1.b").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    self.driver.find_element(By.ID, "id_5-Fcard.a_0.b_0.c").click()
    self.driver.find_element(By.ID, "id_5-Fcard.a_0.b_0.c").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_0.b_1.c").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_1.b_0.c").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_1.b_1.c").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_0.b_0.e").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_0.b_1.e").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_1.b_0.e").send_keys("2")
    self.driver.find_element(By.ID, "id_5-Fcard.a_1.b_1.e").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(14)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_6-Gcard\\.a_0\\.b_0 > li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_6-Gcard\\.a_0\\.b_1 > li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_6-Gcard\\.a_1\\.b_0 > li:nth-child(3) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_6-Gcard\\.a_1\\.b_1 > li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.ID, "id_7-Fcard.a_1.b_0.e_0.b").click()
    self.driver.find_element(By.ID, "id_7-Fcard.a_1.b_0.e_0.b").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.ID, "id_8-a_0.b_0.c_0.d").click()
    self.driver.find_element(By.ID, "id_8-a_0.b_0.c_0.d").send_keys("2")
    self.driver.find_element(By.ID, "id_8-a_0.b_1.c_1.d").send_keys("2")
    self.driver.find_element(By.ID, "id_8-a_1.b_0.e_0.b_0").send_keys("2")
    self.driver.find_element(By.ID, "id_8-a_1.b_0.e_0.b_1").send_keys("2")
    self.driver.find_element(By.ID, "id_8-a_1.b_0.e_0.c").send_keys("3")
    self.driver.find_element(By.ID, "id_8-a_1.b_1.c_1.d").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(12)").click()
  
