package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Abstract implements java.io.Serializable {
  public abstract <R,A> R accept(Abstract.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.AbstractEmpty p, A arg);
    public R visit(clafer.Absyn.AbstractX p, A arg);

  }

}
