package clafer.Absyn; // Java Package generated by the BNF Converter.

public class AssertionX  extends Assertion {
  public final ListExp listexp_;
  public AssertionX(ListExp p1) { listexp_ = p1; }

  public <R,A> R accept(clafer.Absyn.Assertion.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.AssertionX) {
      clafer.Absyn.AssertionX x = (clafer.Absyn.AssertionX)o;
      return this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexp_.hashCode();
  }


}
