package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ClaferId  extends Exp {
  public final Name name_;
  public ClaferId(Name p1) { name_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ClaferId) {
      clafer.Absyn.ClaferId x = (clafer.Absyn.ClaferId)o;
      return this.name_.equals(x.name_);
    }
    return false;
  }

  public int hashCode() {
    return this.name_.hashCode();
  }


}
