package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ClaferX  extends Clafer {
  public final Abstract abstract_;
  public final ListTempModifier listtempmodifier_;
  public final GCard gcard_;
  public final String posident_;
  public final Super super_;
  public final Reference reference_;
  public final Card card_;
  public final Init init_;
  public final Transition transition_;
  public final Elements elements_;
  public ClaferX(Abstract p1, ListTempModifier p2, GCard p3, String p4, Super p5, Reference p6, Card p7, Init p8, Transition p9, Elements p10) { abstract_ = p1; listtempmodifier_ = p2; gcard_ = p3; posident_ = p4; super_ = p5; reference_ = p6; card_ = p7; init_ = p8; transition_ = p9; elements_ = p10; }

  public <R,A> R accept(clafer.Absyn.Clafer.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ClaferX) {
      clafer.Absyn.ClaferX x = (clafer.Absyn.ClaferX)o;
      return this.abstract_.equals(x.abstract_) && this.listtempmodifier_.equals(x.listtempmodifier_) && this.gcard_.equals(x.gcard_) && this.posident_.equals(x.posident_) && this.super_.equals(x.super_) && this.reference_.equals(x.reference_) && this.card_.equals(x.card_) && this.init_.equals(x.init_) && this.transition_.equals(x.transition_) && this.elements_.equals(x.elements_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(37*(37*(37*(37*(37*(this.abstract_.hashCode())+this.listtempmodifier_.hashCode())+this.gcard_.hashCode())+this.posident_.hashCode())+this.super_.hashCode())+this.reference_.hashCode())+this.card_.hashCode())+this.init_.hashCode())+this.transition_.hashCode())+this.elements_.hashCode();
  }


}
