package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Clafer implements java.io.Serializable {
  public abstract <R,A> R accept(Clafer.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ClaferX p, A arg);

  }

}
