package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ClaferUse  extends Element {
  public final Name name_;
  public final Card card_;
  public final Elements elements_;
  public ClaferUse(Name p1, Card p2, Elements p3) { name_ = p1; card_ = p2; elements_ = p3; }

  public <R,A> R accept(clafer.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ClaferUse) {
      clafer.Absyn.ClaferUse x = (clafer.Absyn.ClaferUse)o;
      return this.name_.equals(x.name_) && this.card_.equals(x.card_) && this.elements_.equals(x.elements_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.name_.hashCode())+this.card_.hashCode())+this.elements_.hashCode();
  }


}
