package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Constraint implements java.io.Serializable {
  public abstract <R,A> R accept(Constraint.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ConstraintX p, A arg);

  }

}
