package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Declaration implements java.io.Serializable {
  public abstract <R,A> R accept(Declaration.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.EnumDecl p, A arg);
    public R visit(clafer.Absyn.ElementDecl p, A arg);

  }

}
