package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EDeclAllDisj  extends Exp {
  public final Decl decl_;
  public final Exp exp_;
  public EDeclAllDisj(Decl p1, Exp p2) { decl_ = p1; exp_ = p2; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EDeclAllDisj) {
      clafer.Absyn.EDeclAllDisj x = (clafer.Absyn.EDeclAllDisj)o;
      return this.decl_.equals(x.decl_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.decl_.hashCode())+this.exp_.hashCode();
  }


}
