package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EDeclQuant  extends Exp {
  public final Quant quant_;
  public final Decl decl_;
  public final Exp exp_;
  public EDeclQuant(Quant p1, Decl p2, Exp p3) { quant_ = p1; decl_ = p2; exp_ = p3; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EDeclQuant) {
      clafer.Absyn.EDeclQuant x = (clafer.Absyn.EDeclQuant)o;
      return this.quant_.equals(x.quant_) && this.decl_.equals(x.decl_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.quant_.hashCode())+this.decl_.hashCode())+this.exp_.hashCode();
  }


}
