package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EDouble  extends Exp {
  public final String posdouble_;
  public EDouble(String p1) { posdouble_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EDouble) {
      clafer.Absyn.EDouble x = (clafer.Absyn.EDouble)o;
      return this.posdouble_.equals(x.posdouble_);
    }
    return false;
  }

  public int hashCode() {
    return this.posdouble_.hashCode();
  }


}
