package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EInt  extends Exp {
  public final String posinteger_;
  public EInt(String p1) { posinteger_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EInt) {
      clafer.Absyn.EInt x = (clafer.Absyn.EInt)o;
      return this.posinteger_.equals(x.posinteger_);
    }
    return false;
  }

  public int hashCode() {
    return this.posinteger_.hashCode();
  }


}
