package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Elements implements java.io.Serializable {
  public abstract <R,A> R accept(Elements.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ElementsEmpty p, A arg);
    public R visit(clafer.Absyn.ElementsList p, A arg);

  }

}
