package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ElementDecl  extends Declaration {
  public final Element element_;
  public ElementDecl(Element p1) { element_ = p1; }

  public <R,A> R accept(clafer.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ElementDecl) {
      clafer.Absyn.ElementDecl x = (clafer.Absyn.ElementDecl)o;
      return this.element_.equals(x.element_);
    }
    return false;
  }

  public int hashCode() {
    return this.element_.hashCode();
  }


}
