package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Element implements java.io.Serializable {
  public abstract <R,A> R accept(Element.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.Subclafer p, A arg);
    public R visit(clafer.Absyn.ClaferUse p, A arg);
    public R visit(clafer.Absyn.Subconstraint p, A arg);
    public R visit(clafer.Absyn.Subgoal p, A arg);
    public R visit(clafer.Absyn.SubAssertion p, A arg);

  }

}
