package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ElementsList  extends Elements {
  public final ListElement listelement_;
  public ElementsList(ListElement p1) { listelement_ = p1; }

  public <R,A> R accept(clafer.Absyn.Elements.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ElementsList) {
      clafer.Absyn.ElementsList x = (clafer.Absyn.ElementsList)o;
      return this.listelement_.equals(x.listelement_);
    }
    return false;
  }

  public int hashCode() {
    return this.listelement_.hashCode();
  }


}
