package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class EnumId implements java.io.Serializable {
  public abstract <R,A> R accept(EnumId.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.EnumIdIdent p, A arg);

  }

}
