package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EnumDecl  extends Declaration {
  public final String posident_;
  public final ListEnumId listenumid_;
  public EnumDecl(String p1, ListEnumId p2) { posident_ = p1; listenumid_ = p2; }

  public <R,A> R accept(clafer.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EnumDecl) {
      clafer.Absyn.EnumDecl x = (clafer.Absyn.EnumDecl)o;
      return this.posident_.equals(x.posident_) && this.listenumid_.equals(x.listenumid_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.posident_.hashCode())+this.listenumid_.hashCode();
  }


}
