package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EQuantExp  extends Exp {
  public final Quant quant_;
  public final Exp exp_;
  public EQuantExp(Quant p1, Exp p2) { quant_ = p1; exp_ = p2; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EQuantExp) {
      clafer.Absyn.EQuantExp x = (clafer.Absyn.EQuantExp)o;
      return this.quant_.equals(x.quant_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.quant_.hashCode())+this.exp_.hashCode();
  }


}
