package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EReal  extends Exp {
  public final String posreal_;
  public EReal(String p1) { posreal_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EReal) {
      clafer.Absyn.EReal x = (clafer.Absyn.EReal)o;
      return this.posreal_.equals(x.posreal_);
    }
    return false;
  }

  public int hashCode() {
    return this.posreal_.hashCode();
  }


}
