package clafer.Absyn; // Java Package generated by the BNF Converter.

public class EStr  extends Exp {
  public final String posstring_;
  public EStr(String p1) { posstring_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.EStr) {
      clafer.Absyn.EStr x = (clafer.Absyn.EStr)o;
      return this.posstring_.equals(x.posstring_);
    }
    return false;
  }

  public int hashCode() {
    return this.posstring_.hashCode();
  }


}
