package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class ExInteger implements java.io.Serializable {
  public abstract <R,A> R accept(ExInteger.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ExIntegerAst p, A arg);
    public R visit(clafer.Absyn.ExIntegerNum p, A arg);

  }

}
