package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.TransitionExp p, A arg);
    public R visit(clafer.Absyn.EDeclAllDisj p, A arg);
    public R visit(clafer.Absyn.EDeclAll p, A arg);
    public R visit(clafer.Absyn.EDeclQuantDisj p, A arg);
    public R visit(clafer.Absyn.EDeclQuant p, A arg);
    public R visit(clafer.Absyn.EImpliesElse p, A arg);
    public R visit(clafer.Absyn.LetExp p, A arg);
    public R visit(clafer.Absyn.TmpPatNever p, A arg);
    public R visit(clafer.Absyn.TmpPatSometime p, A arg);
    public R visit(clafer.Absyn.TmpPatLessOrOnce p, A arg);
    public R visit(clafer.Absyn.TmpPatAlways p, A arg);
    public R visit(clafer.Absyn.TmpPatPrecede p, A arg);
    public R visit(clafer.Absyn.TmpPatFollow p, A arg);
    public R visit(clafer.Absyn.TmpInitially p, A arg);
    public R visit(clafer.Absyn.TmpFinally p, A arg);
    public R visit(clafer.Absyn.EIff p, A arg);
    public R visit(clafer.Absyn.EImplies p, A arg);
    public R visit(clafer.Absyn.EOr p, A arg);
    public R visit(clafer.Absyn.EXor p, A arg);
    public R visit(clafer.Absyn.EAnd p, A arg);
    public R visit(clafer.Absyn.LtlU p, A arg);
    public R visit(clafer.Absyn.TmpUntil p, A arg);
    public R visit(clafer.Absyn.LtlW p, A arg);
    public R visit(clafer.Absyn.TmpWUntil p, A arg);
    public R visit(clafer.Absyn.LtlF p, A arg);
    public R visit(clafer.Absyn.TmpEventually p, A arg);
    public R visit(clafer.Absyn.LtlG p, A arg);
    public R visit(clafer.Absyn.TmpGlobally p, A arg);
    public R visit(clafer.Absyn.LtlX p, A arg);
    public R visit(clafer.Absyn.TmpNext p, A arg);
    public R visit(clafer.Absyn.ENeg p, A arg);
    public R visit(clafer.Absyn.ELt p, A arg);
    public R visit(clafer.Absyn.EGt p, A arg);
    public R visit(clafer.Absyn.EEq p, A arg);
    public R visit(clafer.Absyn.ELte p, A arg);
    public R visit(clafer.Absyn.EGte p, A arg);
    public R visit(clafer.Absyn.ENeq p, A arg);
    public R visit(clafer.Absyn.EIn p, A arg);
    public R visit(clafer.Absyn.ENin p, A arg);
    public R visit(clafer.Absyn.EQuantExp p, A arg);
    public R visit(clafer.Absyn.EAdd p, A arg);
    public R visit(clafer.Absyn.ESub p, A arg);
    public R visit(clafer.Absyn.EMul p, A arg);
    public R visit(clafer.Absyn.EDiv p, A arg);
    public R visit(clafer.Absyn.ERem p, A arg);
    public R visit(clafer.Absyn.EGMax p, A arg);
    public R visit(clafer.Absyn.EGMin p, A arg);
    public R visit(clafer.Absyn.ESum p, A arg);
    public R visit(clafer.Absyn.EProd p, A arg);
    public R visit(clafer.Absyn.ECard p, A arg);
    public R visit(clafer.Absyn.EMinExp p, A arg);
    public R visit(clafer.Absyn.EDomain p, A arg);
    public R visit(clafer.Absyn.ERange p, A arg);
    public R visit(clafer.Absyn.EUnion p, A arg);
    public R visit(clafer.Absyn.EUnionCom p, A arg);
    public R visit(clafer.Absyn.EDifference p, A arg);
    public R visit(clafer.Absyn.EIntersection p, A arg);
    public R visit(clafer.Absyn.EIntersectionDeprecated p, A arg);
    public R visit(clafer.Absyn.EJoin p, A arg);
    public R visit(clafer.Absyn.ClaferId p, A arg);
    public R visit(clafer.Absyn.EInt p, A arg);
    public R visit(clafer.Absyn.EDouble p, A arg);
    public R visit(clafer.Absyn.EReal p, A arg);
    public R visit(clafer.Absyn.EStr p, A arg);

  }

}
