package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class GCard implements java.io.Serializable {
  public abstract <R,A> R accept(GCard.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.GCardEmpty p, A arg);
    public R visit(clafer.Absyn.GCardXor p, A arg);
    public R visit(clafer.Absyn.GCardOr p, A arg);
    public R visit(clafer.Absyn.GCardMux p, A arg);
    public R visit(clafer.Absyn.GCardOpt p, A arg);
    public R visit(clafer.Absyn.GCardInterval p, A arg);

  }

}
