package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Goal implements java.io.Serializable {
  public abstract <R,A> R accept(Goal.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.GoalMinDeprecated p, A arg);
    public R visit(clafer.Absyn.GoalMaxDeprecated p, A arg);
    public R visit(clafer.Absyn.GoalMinimize p, A arg);
    public R visit(clafer.Absyn.GoalMaximize p, A arg);

  }

}
