package clafer.Absyn; // Java Package generated by the BNF Converter.

public class InitSome  extends Init {
  public final InitHow inithow_;
  public final Exp exp_;
  public InitSome(InitHow p1, Exp p2) { inithow_ = p1; exp_ = p2; }

  public <R,A> R accept(clafer.Absyn.Init.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.InitSome) {
      clafer.Absyn.InitSome x = (clafer.Absyn.InitSome)o;
      return this.inithow_.equals(x.inithow_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.inithow_.hashCode())+this.exp_.hashCode();
  }


}
