package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class InitHow implements java.io.Serializable {
  public abstract <R,A> R accept(InitHow.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.InitConstant p, A arg);
    public R visit(clafer.Absyn.InitDefault p, A arg);

  }

}
