package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Init implements java.io.Serializable {
  public abstract <R,A> R accept(Init.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.InitEmpty p, A arg);
    public R visit(clafer.Absyn.InitSome p, A arg);

  }

}
