package clafer.Absyn; // Java Package generated by the BNF Converter.

public class LetExp  extends Exp {
  public final VarBinding varbinding_;
  public final Exp exp_;
  public LetExp(VarBinding p1, Exp p2) { varbinding_ = p1; exp_ = p2; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.LetExp) {
      clafer.Absyn.LetExp x = (clafer.Absyn.LetExp)o;
      return this.varbinding_.equals(x.varbinding_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.varbinding_.hashCode())+this.exp_.hashCode();
  }


}
