package clafer.Absyn; // Java Package generated by the BNF Converter.

public class LocIdIdent  extends LocId {
  public final String posident_;
  public LocIdIdent(String p1) { posident_ = p1; }

  public <R,A> R accept(clafer.Absyn.LocId.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.LocIdIdent) {
      clafer.Absyn.LocIdIdent x = (clafer.Absyn.LocIdIdent)o;
      return this.posident_.equals(x.posident_);
    }
    return false;
  }

  public int hashCode() {
    return this.posident_.hashCode();
  }


}
