package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class ModId implements java.io.Serializable {
  public abstract <R,A> R accept(ModId.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ModIdIdent p, A arg);

  }

}
