package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class NCard implements java.io.Serializable {
  public abstract <R,A> R accept(NCard.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.NCardX p, A arg);

  }

}
