package clafer.Absyn; // Java Package generated by the BNF Converter.

public class NCardX  extends NCard {
  public final String posinteger_;
  public final ExInteger exinteger_;
  public NCardX(String p1, ExInteger p2) { posinteger_ = p1; exinteger_ = p2; }

  public <R,A> R accept(clafer.Absyn.NCard.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.NCardX) {
      clafer.Absyn.NCardX x = (clafer.Absyn.NCardX)o;
      return this.posinteger_.equals(x.posinteger_) && this.exinteger_.equals(x.exinteger_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.posinteger_.hashCode())+this.exinteger_.hashCode();
  }


}
