package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class PatternScope implements java.io.Serializable {
  public abstract <R,A> R accept(PatternScope.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.PatScopeBefore p, A arg);
    public R visit(clafer.Absyn.PatScopeAfter p, A arg);
    public R visit(clafer.Absyn.PatScopeBetweenAnd p, A arg);
    public R visit(clafer.Absyn.PatScopeAfterUntil p, A arg);
    public R visit(clafer.Absyn.PatScopeEmpty p, A arg);

  }

}
