package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Quant implements java.io.Serializable {
  public abstract <R,A> R accept(Quant.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.QuantNo p, A arg);
    public R visit(clafer.Absyn.QuantNot p, A arg);
    public R visit(clafer.Absyn.QuantLone p, A arg);
    public R visit(clafer.Absyn.QuantOne p, A arg);
    public R visit(clafer.Absyn.QuantSome p, A arg);

  }

}
