package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Reference implements java.io.Serializable {
  public abstract <R,A> R accept(Reference.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.ReferenceEmpty p, A arg);
    public R visit(clafer.Absyn.ReferenceSet p, A arg);
    public R visit(clafer.Absyn.ReferenceBag p, A arg);

  }

}
