package clafer.Absyn; // Java Package generated by the BNF Converter.

public class ReferenceSet  extends Reference {
  public final Exp exp_;
  public ReferenceSet(Exp p1) { exp_ = p1; }

  public <R,A> R accept(clafer.Absyn.Reference.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.ReferenceSet) {
      clafer.Absyn.ReferenceSet x = (clafer.Absyn.ReferenceSet)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
