package clafer.Absyn; // Java Package generated by the BNF Converter.

public class SubAssertion  extends Element {
  public final Assertion assertion_;
  public SubAssertion(Assertion p1) { assertion_ = p1; }

  public <R,A> R accept(clafer.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.SubAssertion) {
      clafer.Absyn.SubAssertion x = (clafer.Absyn.SubAssertion)o;
      return this.assertion_.equals(x.assertion_);
    }
    return false;
  }

  public int hashCode() {
    return this.assertion_.hashCode();
  }


}
