package clafer.Absyn; // Java Package generated by the BNF Converter.

public class Subconstraint  extends Element {
  public final Constraint constraint_;
  public Subconstraint(Constraint p1) { constraint_ = p1; }

  public <R,A> R accept(clafer.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.Subconstraint) {
      clafer.Absyn.Subconstraint x = (clafer.Absyn.Subconstraint)o;
      return this.constraint_.equals(x.constraint_);
    }
    return false;
  }

  public int hashCode() {
    return this.constraint_.hashCode();
  }


}
