package clafer.Absyn; // Java Package generated by the BNF Converter.

public class Subclafer  extends Element {
  public final Clafer clafer_;
  public Subclafer(Clafer p1) { clafer_ = p1; }

  public <R,A> R accept(clafer.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.Subclafer) {
      clafer.Absyn.Subclafer x = (clafer.Absyn.Subclafer)o;
      return this.clafer_.equals(x.clafer_);
    }
    return false;
  }

  public int hashCode() {
    return this.clafer_.hashCode();
  }


}
