package clafer.Absyn; // Java Package generated by the BNF Converter.

public class Subgoal  extends Element {
  public final Goal goal_;
  public Subgoal(Goal p1) { goal_ = p1; }

  public <R,A> R accept(clafer.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.Subgoal) {
      clafer.Absyn.Subgoal x = (clafer.Absyn.Subgoal)o;
      return this.goal_.equals(x.goal_);
    }
    return false;
  }

  public int hashCode() {
    return this.goal_.hashCode();
  }


}
