package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Super implements java.io.Serializable {
  public abstract <R,A> R accept(Super.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.SuperEmpty p, A arg);
    public R visit(clafer.Absyn.SuperSome p, A arg);

  }

}
