package clafer.Absyn; // Java Package generated by the BNF Converter.

public class TmpFinally  extends Exp {
  public final Exp exp_;
  public TmpFinally(Exp p1) { exp_ = p1; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.TmpFinally) {
      clafer.Absyn.TmpFinally x = (clafer.Absyn.TmpFinally)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
