package clafer.Absyn; // Java Package generated by the BNF Converter.

public class TransitionExp  extends Exp {
  public final Exp exp_1, exp_2;
  public final TransArrow transarrow_;
  public TransitionExp(Exp p1, TransArrow p2, Exp p3) { exp_1 = p1; transarrow_ = p2; exp_2 = p3; }

  public <R,A> R accept(clafer.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.TransitionExp) {
      clafer.Absyn.TransitionExp x = (clafer.Absyn.TransitionExp)o;
      return this.exp_1.equals(x.exp_1) && this.transarrow_.equals(x.transarrow_) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_1.hashCode())+this.transarrow_.hashCode())+this.exp_2.hashCode();
  }


}
