package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class TransGuard implements java.io.Serializable {
  public abstract <R,A> R accept(TransGuard.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.TransGuardX p, A arg);

  }

}
