package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class Transition implements java.io.Serializable {
  public abstract <R,A> R accept(Transition.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.TransitionEmpty p, A arg);
    public R visit(clafer.Absyn.TransitionX p, A arg);

  }

}
