package clafer.Absyn; // Java Package generated by the BNF Converter.

public abstract class VarBinding implements java.io.Serializable {
  public abstract <R,A> R accept(VarBinding.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(clafer.Absyn.VarBindingX p, A arg);

  }

}
