import copy
import logging

from textx import get_location

from core.expressions.expression_base import ExpressionElement

class ConstraintInitializer:
    def __init__(self, workspace):
        self.workspace = workspace
        self.constraint_pattern = {
            'Assign': {
                'Fcard': [],
                'Gcard': [],
                'Value': []
            },
            'Read': {
                'Fcard': [],
                'Gcard': [],
                'Value': []
            },
            'Requires': {
                'Fcard': [],
                'Gcard': [],
                'Value': []
            },
            'Mappings': {},
            'ParentFeature': '',
            'isValidated': False,
            'Expression': '',
            'Precedence': {},
            'Features': {},
            'FeaturesPrec': {},
            'Childs': [],
            'FilterStub': {},
            'State': 'NotValidated'
        }
        self.id_counter = 0

    def parse_constraint(self, constraint, parent_feature):
        """
        Function to define constraints in dict format.

        INPUTS
        constraint (type = textX generated class): constraint's object.
        related_feature (type = string): full name of the feature to which this constraint belongs.

        """
        self.pattern = copy.deepcopy(self.constraint_pattern)
        self.pattern.update({'ParentFeature': parent_feature})
        self.pattern.update({'Expression': self._get_constraint_position(constraint)})

        self.is_term = True
        self._parse_constraint_helper(constraint.name, parent_feature)

        constraint.name.connect_waffle(self)
        constraint = {
            'Object': constraint,
            'Metadata': copy.deepcopy(self.pattern),
            'ID': f'Constraint_{self.id_counter}'
        }

        self.workspace.constraints.update({f'Constraint_{self.id_counter}': constraint})
        self.id_counter += 1
        return constraint

    def _get_constraint_position(self, constraint):
        start_pos = get_location(constraint)
        end_pos = start_pos['col'] + constraint._tx_position_end - constraint._tx_position
        line = self.workspace.description.splitlines()[start_pos['line'] - 1]
        return line[start_pos['col'] - 1: end_pos - 1]

    def _parse_constraint_helper(self, constraint, parent_feature):
        # i.e., prec10, prec8, term, etc.
        cname = constraint.__class__.__name__
        # used for easier flattened representation of an object tree as a dictionary
        self.last_elem_id = 0

        # There is no need to parse strings, integers, etc., this way (term objects)
        if isinstance(constraint, ExpressionElement):
            # list example [operand_1, operation, operand_2] if there is an operation with that precedence class
            # ExpressionElement if not
            # object tree is generated by textX
            if isinstance(constraint.op, list) or isinstance(constraint.op, ExpressionElement):
                res = {}
                # compress to a list for future processing
                if isinstance(constraint.op, list):
                    if len(elements := constraint.op) > 1:
                        self.is_term = False
                else:
                    elements = [constraint.op]

                for index, op in enumerate(elements):
                    subres = self._parse_constraint_helper(op, parent_feature)

                    # feature processing pipeline for appropriate elements of an object tree
                    if isinstance(subres, str) and len(elements) >= 1 and subres not in self.workspace.KEYWORDS:
                        fnames, card_keyword, childs_keyword, fname_keyword, is_feature = self._parse_feature_name(subres,
                                                                                                                   parent_feature)
                        if is_feature is True:
                            subres = {}
                            for index, fname in enumerate(fnames):
                                if childs_keyword is True and fname == fnames[0]:
                                    ftype = 'Childs'
                                elif fname_keyword is True:
                                    ftype = 'Fname'
                                elif card_keyword in ['fcard', 'gcard']:
                                    ftype = card_keyword.capitalize()
                                else:
                                    ftype = 'Value'
                                subres.update({fname: ftype})
                            self.pattern['Features'].update({self.last_elem_id: subres})
                            if self.is_term is True:
                                subres[fname] = 'Fcard'
                                res.update({index: subres})
                                res.update({'Class': cname})
                                self.pattern['FeaturesPrec'].update({fname: ['term']})
                                self.pattern['Precedence'].update({id(constraint): res})
                    res.update({index: subres})

                # update constraint metadata if there is an operation detected
                if len(elements) > 1:
                    res.update({'Class': cname})
                    for md in res.values():
                        if isinstance(md, dict):
                            for fname in md.keys():
                                if fname not in self.pattern['FeaturesPrec'].keys():
                                    self.pattern['FeaturesPrec'].update({fname: [cname]})
                                else:
                                    self.pattern['FeaturesPrec'][fname].append(cname)
                                if cname in self.workspace.PREC_BOOL:
                                    md[fname] = 'Fcard'
                    self.pattern['Precedence'].update({id(constraint): res})
                return id(constraint) if len(elements) > 1 else subres
            else:
                self.last_elem_id = id(constraint)
                return constraint.op
        else:
            return constraint

    def _parse_feature_name(self, name, parent_feature):

        # quotation mark explicitly defines a regular string that is not a feature name
        if '\'' in name or '\"' in name:
            return [name], False, False, False, False

        # for keywords usage checks
        # keywords usage example: childs.self, fcard.A, fname.A.B, etc.
        # Waffle analyzes keyword positions in a split feature name with a dot separator
        # firstly it checks occurrence of the following keywords, i.e., how many times any keyword is present
        indices = {
            'childs': [],
            'self': [],
            'parent': [],
            'fname': [],
            'fcard': [],
            'gcard': [],
            'gfcard': []
        }
        childs_keyword, fname_keyword = False, False
        # for keyword position check
        feature_indices = []
        for index, part in enumerate(split := name.split('.')):
            if part in indices.keys():
                indices[part].append(index)
            else:
                feature_indices.append(index)

        # keyword occurrence checks
        # only one occurrence of any keyword is allowed, i.e., no self.self, except parent keyword
        # parent keyword can be used many times, each occurrence goes up a level in the tree
        for k, v in indices.items():
            if repeats := len(v) > 1 and k != 'parent':
                logging.error(f'Keyword {k} appears {repeats} times.')

        # usage of relative feature indication keywords is limited, instead of 'parent.self' or 'self.parent' use 'parent' only
        if len(indices['self']) > 1 and len(indices['parent']) > 1:
            logging.error('Keywords "self" and "parent" can not appear at the same time.')

        # usage of feature attribute indication keywords is limited since they point at different properties to call
        if len(indices['fcard'] + indices['gcard'] + indices['gfcard'] + indices['childs'] + indices['fname']) > 1:
            logging.error('Keywords "fcard", "gcard", "fname", "childs", and "gfcard" can not appear at the same time.')

        # keyword position check
        # all keywords must be placed before feature name!
        # card_keyword and rel_keyword are used to extract feature name only, i.e., fcard.A.B -> A.B
        card_keyword = None
        # feature attribute indication keyword always must be placed at the first position i.e., fcard.A, gcard.A.B, etc.
        for keyword in ['fcard', 'gcard', 'gfcard', 'childs', 'fname']:
            if len(indices[keyword]) > 0 and indices[keyword][0] != 0:
                logging.error(f'Wrong position of keyword! {keyword}.')
            elif len(indices[keyword]) > 0:
                card_keyword = keyword

        rel_keyword = None
        # relative feature indication keywords are used to simplify feature references in deep trees
        # example for constraint assigned to feature A.B.C.D:
        # 'A.B.C.D.E' -> 'self.E', 'A.B.C.F' -> 'parent.F', 'A.B.G' -> 'parent.parent.G'
        # also relative feature indication works well with multiple cardinalities, inticating appropriate subtree copy
        for keyword in ['self', 'parent']:
            # relative feature indication keyword must be either at the first place
            # or second if there is a feature attribute indication
            if len(indices[keyword]) > 0:
                if not (indices[keyword][0] == 0 or (indices[keyword][0] == 1 and card_keyword is not None)):
                    logging.error(f'Wrong position of keyword!! {keyword}.')
                rel_keyword = (keyword, len(indices[keyword]))

            # in case of combined usage of relative and absolute feature indication, relative goes first
            # e.g., self.B referencing to a feature B of appropriate subtree
            # 'self.B' or 'fcard.self.B'
            if len(feature_indices) > 0:
                for pos in indices[keyword]:
                    if pos > feature_indices[0]:
                        logging.error(f'Wrong position of keyword!!! {keyword}.')

        # for defining full feature name taking into account all keywords
        skip_chars_card = 1 if card_keyword is not None else 0
        skip_chars_rel = rel_keyword[1] if rel_keyword is not None else 0

        par_split = parent_feature.split('.')
        par_split_last_index = len(par_split) - (rel_keyword[1] if rel_keyword is not None and rel_keyword[0] == 'parent' else 0)
        repl_chars_res = par_split[:par_split_last_index]
        self_name = '.'.join(repl_chars_res + split[skip_chars_card + skip_chars_rel:])
        full_name = '.'.join(split[skip_chars_card + skip_chars_rel:])

        # check whether this is a feature (is it present in the workspace)
        for check in [self_name, full_name, name]:
            try:
                self.workspace.read_feature_data(check)
                is_feature = True
                res = check
                break
            except ValueError:
                res = name
                is_feature = False
                # TODO proper logging
                # logging.error(f'{name} | {full_name} | {self_name} is not a correct feature | {par_split} | {repl_chars_res}')
        if card_keyword == 'childs':
            childs = self.workspace.get_feature_childrens(res, filter_active=False)
            res = [res] + childs
            card_keyword = 'fcard'
            childs_keyword = True
        elif card_keyword == 'fname':
            res = [res]
            card_keyword = 'fcard'
            fname_keyword = True
        else:
            res = [res]
        return res, card_keyword, childs_keyword, fname_keyword, is_feature
