# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBRISEUPD():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bRISEUPD(self):
    # Test name: BRISE_UPD
    # Step # | name | target | value
    # 1 | open | /wizard/test/ | 
    self.driver.get("http://127.0.0.1:8000/wizard/test/")
    # 2 | setWindowSize | 1853x1053 | 
    self.driver.set_window_size(1853, 1053)
    # 3 | click | css=input:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    # 4 | type | id=id_0-fcard_Predictor.Models | 1
    self.driver.find_element(By.ID, "id_0-fcard_Predictor.Models").send_keys("1")
    # 5 | type | id=id_0-fcard_StopCondition.QuantityBasedSC | 1
    self.driver.find_element(By.ID, "id_0-fcard_StopCondition.QuantityBasedSC").send_keys("1")
    # 6 | type | id=id_0-fcard_StopCondition.BadConfigurationBasedSC | 1
    self.driver.find_element(By.ID, "id_0-fcard_StopCondition.BadConfigurationBasedSC").send_keys("1")
    # 7 | type | id=id_0-fcard_StopCondition.ImprovementBasedSC | 1
    self.driver.find_element(By.ID, "id_0-fcard_StopCondition.ImprovementBasedSC").send_keys("1")
    # 8 | type | id=id_0-fcard_StopCondition.TimeBasedSC | 1
    self.driver.find_element(By.ID, "id_0-fcard_StopCondition.TimeBasedSC").send_keys("1")
    # 9 | click | css=input:nth-child(8) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    # 10 | click | css=li:nth-child(1) > label | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > label").click()
    # 11 | click | css=li:nth-child(2) > label | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > label").click()
    # 12 | click | id=id_1-gcard_OD_2 | 
    self.driver.find_element(By.ID, "id_1-gcard_OD_2").click()
    # 13 | click | id=id_1-gcard_OD_3 | 
    self.driver.find_element(By.ID, "id_1-gcard_OD_3").click()
    # 14 | click | id=id_1-gcard_OD_4 | 
    self.driver.find_element(By.ID, "id_1-gcard_OD_4").click()
    # 15 | click | id=id_1-gcard_Repeater | 
    self.driver.find_element(By.ID, "id_1-gcard_Repeater").click()
    # 16 | select | id=id_1-gcard_Repeater | label=AcceptableErrorBasedRepeater
    dropdown = self.driver.find_element(By.ID, "id_1-gcard_Repeater")
    dropdown.find_element(By.XPATH, "//option[. = 'AcceptableErrorBasedRepeater']").click()
    # 17 | click | css=#id_1-gcard_Repeater > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_1-gcard_Repeater > option:nth-child(2)").click()
    # 18 | click | id=id_1-gcard_Predictor.Models.MAB.Parameters.cType | 
    self.driver.find_element(By.ID, "id_1-gcard_Predictor.Models.MAB.Parameters.cType").click()
    # 19 | click | css=#id_1-gcard_Predictor\.Models\.MAB\.Parameters\.cType > option:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_1-gcard_Predictor\\.Models\\.MAB\\.Parameters\\.cType > option:nth-child(1)").click()
    # 20 | click | id=id_1-gcard_Predictor.Models | 
    self.driver.find_element(By.ID, "id_1-gcard_Predictor.Models").click()
    # 21 | click | css=#id_1-gcard_Predictor\.Models > option:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_1-gcard_Predictor\\.Models > option:nth-child(1)").click()
    # 22 | click | css=input:nth-child(9) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    # 23 | type | id=id_2-StopCondition.BadConfigurationBasedSC.Name | BCBSC
    self.driver.find_element(By.ID, "id_2-StopCondition.BadConfigurationBasedSC.Name").send_keys("BCBSC")
    # 24 | type | id=id_2-StopCondition.BadConfigurationBasedSC.Parameters.MaxBadConfigurations | 10
    self.driver.find_element(By.ID, "id_2-StopCondition.BadConfigurationBasedSC.Parameters.MaxBadConfigurations").send_keys("10")
    # 25 | type | id=id_2-StopCondition.GuaranteedSC.Name | GSC
    self.driver.find_element(By.ID, "id_2-StopCondition.GuaranteedSC.Name").send_keys("GSC")
    # 26 | type | id=id_2-StopCondition.ImprovementBasedSC.Name | IBSC
    self.driver.find_element(By.ID, "id_2-StopCondition.ImprovementBasedSC.Name").send_keys("IBSC")
    # 27 | type | id=id_2-StopCondition.ImprovementBasedSC.Parameters.MaxConfigsWithoutImprovement | 5
    self.driver.find_element(By.ID, "id_2-StopCondition.ImprovementBasedSC.Parameters.MaxConfigsWithoutImprovement").send_keys("5")
    # 28 | type | id=id_2-StopCondition.QuantityBasedSC.Name | QBSC
    self.driver.find_element(By.ID, "id_2-StopCondition.QuantityBasedSC.Name").send_keys("QBSC")
    # 29 | type | id=id_2-StopCondition.QuantityBasedSC.Parameters.MaxConfigs | 15
    self.driver.find_element(By.ID, "id_2-StopCondition.QuantityBasedSC.Parameters.MaxConfigs").send_keys("15")
    # 30 | type | id=id_2-StopCondition.TimeBasedSC.Name | TBSC
    self.driver.find_element(By.ID, "id_2-StopCondition.TimeBasedSC.Name").send_keys("TBSC")
    # 31 | type | id=id_2-StopCondition.TimeBasedSC.Parameters.MaxRunTime | 10
    self.driver.find_element(By.ID, "id_2-StopCondition.TimeBasedSC.Parameters.MaxRunTime").send_keys("10")
    # 32 | type | id=id_2-StopCondition.TimeBasedSC.Parameters.TimeUnit | minutes
    self.driver.find_element(By.ID, "id_2-StopCondition.TimeBasedSC.Parameters.TimeUnit").send_keys("minutes")
    # 33 | click | css=input:nth-child(15) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(15)").click()
    # 34 | click | id=id_3-StopConditionTriggerLogic.Expression | 
    self.driver.find_element(By.ID, "id_3-StopConditionTriggerLogic.Expression").click()
    # 35 | type | id=id_3-StopConditionTriggerLogic.Expression | (QuantityBased and Guaranteed and ImprovementBased) or BadConfigurationBased or TimeBased
    self.driver.find_element(By.ID, "id_3-StopConditionTriggerLogic.Expression").send_keys("(QuantityBased and Guaranteed and ImprovementBased) or BadConfigurationBased or TimeBased")
    # 36 | type | id=id_3-StopConditionTriggerLogic.InspectionParameters.RepetitionPerion | 1
    self.driver.find_element(By.ID, "id_3-StopConditionTriggerLogic.InspectionParameters.RepetitionPerion").send_keys("1")
    # 37 | type | id=id_3-StopConditionTriggerLogic.InspectionParameters.TimeUnit | seconds
    self.driver.find_element(By.ID, "id_3-StopConditionTriggerLogic.InspectionParameters.TimeUnit").send_keys("seconds")
    # 38 | click | css=input:nth-child(8) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    # 39 | click | id=id_4-Predictor.Models.TPE.Parameters.BandwidthFactor | 
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.BandwidthFactor").click()
    # 40 | type | id=id_4-Predictor.Models.TPE.Parameters.BandwidthFactor | 3
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.BandwidthFactor").send_keys("3")
    # 41 | type | id=id_4-Predictor.Models.TPE.Parameters.MinBandwirth | 0.001
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.MinBandwirth").send_keys("0.001")
    # 42 | type | id=id_4-Predictor.Models.TPE.Parameters.RandomFraction | 0
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.RandomFraction").send_keys("0")
    # 43 | type | id=id_4-Predictor.Models.TPE.Parameters.SamplingSize | 96
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.SamplingSize").send_keys("96")
    # 44 | type | id=id_4-Predictor.Models.TPE.Parameters.TopNPercent | 30
    self.driver.find_element(By.ID, "id_4-Predictor.Models.TPE.Parameters.TopNPercent").send_keys("30")
    # 45 | type | id=id_4-Predictor.WindowSize | 1.0
    self.driver.find_element(By.ID, "id_4-Predictor.WindowSize").send_keys("1.0")
    # 46 | click | css=input:nth-child(11) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()
    # 47 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.BaseAcceptableErrors | 5
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.BaseAcceptableErrors").send_keys("5")
    # 48 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.ConfidenceLevels | 0.95
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.ConfidenceLevels").send_keys("0.95")
    # 49 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.DevicesAccuracyClasses | 0
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.DevicesAccuracyClasses").send_keys("0")
    # 50 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.DevicesScaleAccuracies | 0
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.DevicesScaleAccuracies").send_keys("0")
    # 51 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.ExperimentAwareness.MaxAcceptableErrors | 50
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.ExperimentAwareness.MaxAcceptableErrors").send_keys("50")
    # 52 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.ExperimentAwareness.RatiosMax | 10
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.ExperimentAwareness.RatiosMax").send_keys("10")
    # 53 | click | css=li:nth-child(1) > label | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > label").click()
    # 54 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.MaxFailedTasksPerConfiguration | 5
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.MaxFailedTasksPerConfiguration").send_keys("5")
    # 55 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.MaxTasksPerConfiguration | 10
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.MaxTasksPerConfiguration").send_keys("10")
    # 56 | type | id=id_5-Repeater.AcceptableErrorBasedRepeater.MinTasksPerConfiguration | 2
    self.driver.find_element(By.ID, "id_5-Repeater.AcceptableErrorBasedRepeater.MinTasksPerConfiguration").send_keys("2")
    # 57 | click | css=input:nth-child(15) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(15)").click()
    # 58 | type | id=id_6-OD.Chauvenet.MaxActiveNumberOfTasks | 10000
    self.driver.find_element(By.ID, "id_6-OD.Chauvenet.MaxActiveNumberOfTasks").send_keys("10000")
    # 59 | type | id=id_6-OD.Chauvenet.MinActiveNumberOfTasks | 3
    self.driver.find_element(By.ID, "id_6-OD.Chauvenet.MinActiveNumberOfTasks").send_keys("3")
    # 60 | type | id=id_6-OD.Dixon.MaxActiveNumberOfTasks | 30
    self.driver.find_element(By.ID, "id_6-OD.Dixon.MaxActiveNumberOfTasks").send_keys("30")
    # 61 | type | id=id_6-OD.Dixon.MinActiveNumberOfTasks | 3
    self.driver.find_element(By.ID, "id_6-OD.Dixon.MinActiveNumberOfTasks").send_keys("3")
    # 62 | type | id=id_6-OD.Grubbs.MaxActiveNumberOfTasks | 10000
    self.driver.find_element(By.ID, "id_6-OD.Grubbs.MaxActiveNumberOfTasks").send_keys("10000")
    # 63 | type | id=id_6-OD.Grubbs.MinActiveNumberOfTasks | 3
    self.driver.find_element(By.ID, "id_6-OD.Grubbs.MinActiveNumberOfTasks").send_keys("3")
    # 64 | type | id=id_6-OD.Mad.MaxActiveNumberOfTasks | 10000
    self.driver.find_element(By.ID, "id_6-OD.Mad.MaxActiveNumberOfTasks").send_keys("10000")
    # 65 | type | id=id_6-OD.Mad.MinActiveNumberOfTasks | 3
    self.driver.find_element(By.ID, "id_6-OD.Mad.MinActiveNumberOfTasks").send_keys("3")
    # 66 | type | id=id_6-OD.Quartiles.MaxActiveNumberOfTasks | 10000
    self.driver.find_element(By.ID, "id_6-OD.Quartiles.MaxActiveNumberOfTasks").send_keys("10000")
    # 67 | type | id=id_6-OD.Quartiles.MinActiveNumberOfTasks | 3
    self.driver.find_element(By.ID, "id_6-OD.Quartiles.MinActiveNumberOfTasks").send_keys("3")
    # 68 | click | css=input:nth-child(15) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(15)").click()
    # 69 | type | id=id_7-SelectionAlgorithm.type | Sobol
    self.driver.find_element(By.ID, "id_7-SelectionAlgorithm.type").send_keys("Sobol")
    # 70 | click | css=input:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    # 71 | type | id=id_8-General.NumberOfWorkers | 3
    self.driver.find_element(By.ID, "id_8-General.NumberOfWorkers").send_keys("3")
    # 72 | type | id=id_8-General.result_storage | ./Results/
    self.driver.find_element(By.ID, "id_8-General.result_storage").send_keys("./Results/")
    # 73 | click | css=input:nth-child(7) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
  
